Failure # 1 (occurred at 2023-12-01_10-17-29)
[36mray::ImplicitFunc.train()[39m (pid=27609, ip=171.65.93.126, actor_id=52c9a0bbdf2531ea296ef0fb01000000, repr=objective)
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 400, in train
    raise skipped from exception_cause(skipped)
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/air/_internal/util.py", line 91, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 383, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 822, in _trainable_func
    output = fn()
  File "/home/nrubio/Desktop/junction_pressure_differentials/util/regression/method_tuning.py", line 31, in objective
    reg_steady, dP_loss_val_steady, dP_loss_train_steady = train_dt_model_steady(anatomy, num_geos_steady, seed = 0)
  File "/home/nrubio/Desktop/junction_pressure_differentials/util/regression/dec_tree.py", line 18, in train_dt_model_steady
    dt = DecisionTreeRegressor(random_state=0, max_depth=hyperparams["max_depth"], min_samples_leaf =hyperparams["min_samples_leaf"] ).fit(np.asarray(train_input), np.asarray(train_output))
KeyError: 'max_depth'
