Failure # 1 (occurred at 2023-10-19_15-44-51)
[36mray::ImplicitFunc.train()[39m (pid=13209, ip=171.65.93.126, actor_id=cc932faee98975f1093d5efb01000000, repr=objective)
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 400, in train
    raise skipped from exception_cause(skipped)
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/air/_internal/util.py", line 91, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 383, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 822, in _trainable_func
    output = fn()
  File "/home/nrubio/Desktop/junction_pressure_differentials/util/regression/neural_network/nn_opt.py", line 21, in objective
    train.report({"inference_performance": float(metric)})  # Report to Tune
TypeError: float() argument must be a string or a number, not 'tuple'
