Failure # 1 (occurred at 2023-12-25_13-17-44)
[36mray::ImplicitFunc.train()[39m (pid=19752, ip=171.65.93.126, actor_id=951c606199b6abf27fa1129e01000000, repr=objective)
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 400, in train
    raise skipped from exception_cause(skipped)
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/air/_internal/util.py", line 91, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 383, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/home/nrubio/anaconda3/envs/tf-gpu-cuda10/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 822, in _trainable_func
    output = fn()
  File "/home/nrubio/Desktop/junction_pressure_differentials/util/regression/neural_network/nn_opt.py", line 22, in objective
    train_mse, val_mse, model_name = train_and_val_gnn(anatomy = "Aorta_rand", num_geos = 127,  seed = 0, unsteady = True, unsteady_opt = False, config = config)
  File "/home/nrubio/Desktop/junction_pressure_differentials/util/regression/neural_network/launch_training.py", line 49, in train_and_val_gnn
    train_dataset = load_dict(train_dataset_loc)
  File "/home/nrubio/Desktop/junction_pressure_differentials/util/regression/neural_network/training_util.py", line 28, in load_dict
    f = open(dir, "rb"); scaling_dict = pickle.load(f)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nrubio/Desktop/junction_pressure_differentials/data/dgl_datasets/Aorta_rand/train_Aorta_rand_num_geos_127_seed_0_dataset'
